---
title: "Homework 8"
author: "Anthony Ferraro"
output:
  html_document:
    df_print: paged
linkcolor: blue
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, fig.align = "center", out.width = "50%", warning = FALSE, message = FALSE)

library(tidyverse)
library(knitr)

theme_set(theme_minimal())

library(Lock5Data)
data("StudentSurvey")
```


#### Making a BMI Column
```{r}
knitr::kable(StudentSurvey %>% 
    mutate(BMI = 701 * (Weight / (Height ^ 2))) %>%
    select(Sex, Weight, Height, BMI) %>%
    head(n = 10))

```

^[Question 1 Complete]


#### Labeling Each Student's BMI
```{r}
BMIStudent_Survey = StudentSurvey %>% 
    mutate(BMI = 701 * (Weight / (Height ^ 2))) %>%
    select(Sex, Weight, Height, BMI)

knitr::kable(BMIStudent_Survey %>%
  mutate(
    BMI_category = cut(
      BMI,
      breaks = c(-Inf, 18.5, 25, 30, Inf),
      labels = c("Underweight", "Healthy Weight", "Overweight", "Obese")
    )
  ) %>%
  head(n = 10))
```

^[Question 2 Complete]


#### Finding Lowest and Highest BMI for Male and Female
```{r}
knitr::kable(BMIStudent_Survey %>%
    group_by(Sex) %>%
    summarize(HighestBMI = max(BMI, na.rm = TRUE),
              LowestBMI = min(BMI, na.rm = TRUE)))
    
```

^[Question 3 Complete]


#### Finding Value of Higher SAT Score for Each Student
```{r}
knitr::kable(StudentSurvey %>%
    mutate(HigherSAT = pmax(VerbalSAT, MathSAT, na.rm = TRUE),
           .keep = "used") %>%
    head(n = 6))
```

^[Question 4 Complete]



#### Finding the Z-Score of Each Student's SAT Score
```{r}
knitr::kable(StudentSurvey %>%
    mutate(
        z_score = ((SAT - mean(SAT)) / sd(SAT)),
        .keep = "used"
    ) %>%
    head(n = 6))
```

^[Question 5 Complete]












